name: riverpod_anime
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  build_runner: ^2.1.11
  dio: ^4.0.6
  flutter_hooks: ^0.18.4
  freezed: ^2.0.3+1
  hooks_riverpod: ^1.0.4
  json_serializable: ^6.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
